substitutions:
  name: "esp-salon02"
  devicename: "esp-salon02"
  friendly_name: "esp-salon02"
  idname: "esp_salon02" # "_" est le seul caractère autoriser
  entity_name: "Radar" # Leave empty if you want entities named "Target..." otherwise put "Room" to have an entity named "Room Target..."
  # specify below pin numbers of your LD2450
  tx_pin_ld2450: GPIO17
  rx_pin_ld2450: GPIO16
  board: esp32dev
  type: arduino # ou arduino esp-idf
  loglevel: DEBUG #VERY_VERBOSE
  static_ip: 192.168.1.XX  # <-- Remplacez par l'IP de votre ESP
  # ==========================================
  #   SURCHARGE PERFORMANCE (depuis .ld2450.yaml)
  # ==========================================
  # ---> MODE RÉGLAGE (tracé fluide sur le Dashboard)
  # uart_throttle_ms: "250"
  #
  # ---> MODE PRODUCTION (valeur actuelle)
  # uart_throttle_ms: "1500"
  # ==========================================
  uart_throttle_ms: "1500"

packages:
  base: !include .base.yaml
  ld2450: !include .ld2450.yaml






# Enable Home Assistant API
api:
  encryption:
    key: "VOTRE_CLE_API_ICI"  # <-- Générée par ESPHome
